apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: production
  labels:
    app: web-app
    component: web
spec:
  selector:
    app: web-app
    component: web
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP  # Внутренний сервис, для внешнего доступа нужен Ingress
  sessionAffinity: None
  publishNotReadyAddresses: false  # Не отправлять трафик на неподготовленные поды
